#!/bin/sh


STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(html|js|ts|jsx|tsx|css|scss|json|md)$')

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

# PRETTIER
PRETTIER="./frontend/kaeuzchen-workspace/node_modules/.bin/prettier"

echo "Running prettier on staged files..."

if [ ! -f "$PRETTIER" ]; then
  echo "Prettier wurde nicht gefunden: $PRETTIER"
  exit 1
fi

for FILE in $STAGED_FILES; do
  "$PRETTIER" --write "$FILE"
  git add "$FILE"
done


exit 0